config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'custom_sessions' }

  get 'guru', to: 'users#show'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline_form, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image_url, :criterion, :param, presence: true

  enum criterions: %i[first_try all_category all_level]
end

app/controllers/admin/badges_controller.rb
class Admin::BadgesController < Admin::BaseController
  before_action :find_badge, only: %i[show edit update destroy]
  before_action :set_tests_and_categories, only: %i[new create]

  def index
    @badges = Badge.all
  end

  def show
  end

  def new
    @badge = Badge.new
  end

  def create
    @badge = Badge.new(badge_params)

    if @badge.save
      redirect_to admin_badges_path, notice: t('.notice')
    else
      render :new
    end
  end

  def edit; end

  def update
    if @badge.update(badge_params)
      redirect_to admin_badges_path, notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    @badge.destroy!

    redirect_to admin_badges_path, notice: t('.notice')
  end

  private

  def find_badge
    @badge = Badge.find(params[:id])
  end

  def badge_params
    params.require(:badge).permit(:name, :image_url, :criterion, :param)
  end

  def set_tests_and_categories
    @categories = Category.all
    @tests = Test.all
  end
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  def index
    @badges = Badge.all
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def criterions_collection
    Badge.criterions.map {|item, _val| [t("admin.badges.#{item}"), item]}
  end

  def tests_with_any
    [[0, t('admin.badges.any')]] + @tests.pluck(:id, :title)
  end
end

app/views/admin/badges/_badge.html.erb
<tr>
  <td class="align-middle"><%= badge.name %></td>
  <td class="align-middle"><%= image_tag badge.image_url, class: "badge_icon" %></td>
  <td class="align-middle"><%= badge.criterion %></td>
  <td class="align-middle"><%= badge.param %></td>
  <td class="align-middle"><%= link_to t('.edit'), edit_admin_badge_path(badge) %></td>
  <td class="align-middle"><%= link_to t('.delete'), admin_badge_path(badge),
                                       method: :delete,
                                       data: {confirm: t('.sure')} %>
  </td>

</tr>

app/views/admin/badges/_badge_table.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.image_url') %></th>
      <th><%= t('.criterion') %></th>
      <th><%= t('.param') %></th>
      <th colspan="2"><%= t('.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <%= render partial: 'admin/badges/badge', collection: badge %>
  </tbody>
</table>

app/views/admin/badges/_form.html.erb
<div class="row m-3">
  <%= content_tag :div, id: "data-categories", data: {categories: @categories.pluck(:id, :title)} do %>
  <% end %>
  <%= content_tag :div, id: "data-tests", data: {tests: tests_with_any} do %>
  <% end %>
  <%= content_tag :div, id: "data-levels", data: {levels: levels.to_a} do %>
  <% end %>
  <div class="col- col-sm-12 col-md-6">
    <%= form_with model: [:admin, @badge], local: true do |form| %>
      <%= render 'shared/errors', resource: @badge %>

      <div class="form-group">
        <%= form.label :name %><br>
        <%= form.text_field :name, autofocus: true, placeholder: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :image_url %><br>
        <%= form.text_field :image_url, placeholder: true, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :criterion %><br>
        <%= form.select :criterion, criterions_collection, {prompt: t('helpers.select.badge.criterion')}, {class: 'form-control'} %>
      </div>

      <div class="form-group hide" id="param">
        <%= form.label :param %><br>
        <select class="form-control" name="badge[param]" id="badge_param">
          <%= options_for_select(levels.invert.to_a) %>
        </select>
      </div>

      <%= form.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/badges/edit.html.erb
<h1><%= t('.header_html', title: @badge.name) %></h1>

<%= render 'form' %>

app/views/admin/badges/index.html.erb
<h1><%= t('.header') %></h1>

<%= link_to t('.create_new'), new_admin_badge_path %>
<hr><br>

<%= render 'shared/errors', resource: @badge %>

<%= render partial: 'admin/badges/badge_table', locals: { badge: @badges } %>

app/views/admin/badges/new.html.erb
<h1><%= t('.header') %></h1>

<%= render 'form' %>

app/views/admin/badges/show.html.erb
<h1><%= t('.header_html', title: @badge.name) %></h1>