config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'custom_sessions' }

  get 'guru', to: 'users#show'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline_form, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end
end

app/models/admin.rb
class Admin < User
  validates :name, :surname, presence: true
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_ANSWERS = 4

  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  scope :right_answers, -> { where(correct: true) }

  private

  def validate_answers_quantity
    if question.answers.count >= MAX_ANSWERS
      errors.add(:answers_quantity, I18n.t('activerecord.errors.messages.max_answers', max: MAX_ANSWERS))
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
# frozen_string_literal: true

class Badge < ApplicationRecord
  has_many :user_badges, dependent: :destroy
  has_many :users, through: :user_badges

  validates :name, :image_url, :criterion, :param, presence: true

  enum criterions: %i[first_try all_category all_level]
end

app/models/category.rb
class Category < ApplicationRecord
  default_scope { order(title: :asc) }

  has_many :tests, dependent: :restrict_with_exception

  validates :title, presence: true
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Model

  attr_accessor :name, :email, :message

  validates :name, :email, :message, presence: true
end

app/models/gist.rb
class Gist < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test.rb
# frozen_string_literal: true

class Test < ApplicationRecord
  LEVELS = %i[easy elementary advanced hard pro].freeze

  belongs_to :category
  belongs_to :author, class_name: 'User'
  has_many :questions, dependent: :destroy
  has_many :test_passages, dependent: :destroy
  has_many :users, through: :test_passages, dependent: :destroy

  validates :title, presence: true, uniqueness: { scope: :level }
  validates :level, :duration, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  before_create :set_duration_in_seconds

  scope :easy, -> { where(level: 0..1) }
  scope :medium, -> { where(level: 2..4) }
  scope :hard, -> { where(level: 5..Float::INFINITY) }

  scope :tests_by_category, lambda { |cat|
    joins(:category)
      .where(categories: { title: cat })
      .order(title: :desc)
  }

  def self.by_category(category)
    tests_by_category(category).pluck(:title)
  end

  def total_questions
    questions.size
  end

  private

  def set_duration_in_seconds
    self.duration = duration * 60
  end
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  # процент правильных ответов выше которого тест засчитывается успешно пройденным
  SUCCESS_VALUE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question
  before_save :calc_result, if: :completed?

  def accept!(answer_ids)
    if in_time?
      self.score += 1 if correct_answer?(answer_ids)
      save!
    else
      self.current_question = nil
    end
  end

  def completed?
    current_question.nil?
  end

  def result_percentage
    score * 100 / test.total_questions
  end

  def successful?
    in_time? && result_percentage >= SUCCESS_VALUE if completed?
  end

  def question_number
    test.questions.order(:id).where('id <= ?', current_question).size
  end

  def passage_duration
    (Time.current - self.created_at).to_i
  end

  def remain_duration
    self.test.duration - passage_duration
  end

  private

  def before_validation_set_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.right_answers
  end

  def calc_result
    self.result = result_percentage
  end

  def in_time?
    duration = test.duration

    duration.zero? || passage_duration <= duration
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         :confirmable

  has_many :test_passages, dependent: :destroy
  has_many :tests, through: :test_passages, dependent: :destroy

  has_many :authorships, class_name: 'Test', foreign_key: 'author_id', dependent: :nullify

  has_many :user_badges, dependent: :destroy
  has_many :badges, through: :user_badges

  validates :name, presence: true

  def tests_by_level(level)
    tests.where(level: level)
  end

  def test_passage(test)
    test_passages.order(id: :desc).find_by(test: test)
  end

  def admin?
    is_a?(Admin)
  end
end

app/models/user_badge.rb
class UserBadge < ApplicationRecord
  belongs_to :user
  belongs_to :badge
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!, only: %i[start]
  before_action :find_test, only: %i[start]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_from_test_not_found

  def index
    @tests = Test.all
  end

  def start
    current_user.tests.push(@test)

    redirect_to current_user.test_passage(@test)
  end

  private

  def find_test
    @test = Test.find(params[:id])
  end

  def rescue_from_test_not_found
    redirect_to tests_path, alert: t('.alert.not_found')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :show

  def show; end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.current.year
  end

  def github_url(author, repo)
    "https://github.com/#{author}/#{repo}"
  end

  def root_link
    link_to t('helpers.application.to_root'), root_path
  end

  def badges_link
    link_to t('helpers.application.to_badges'), badges_path
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
  def criterions_collection
    Badge.criterions.map {|item, _val| [t("admin.badges.#{item}"), item]}
  end

  def tests_with_any
    [[0, t('admin.badges.any')]] + @tests.pluck(:id, :title)
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    act = question.new_record? ? t('helpers.question.create') : t('helpers.question.edit')
    t('helpers.question.qheader', act: act, title: question.test.title)
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def total_questions_helper
    t('helpers.test_passage.total', total: @test_passage.test.total_questions)
  end

  def result_message(result)
    if @test_passage.successful?
      content_tag(:h2, t('helpers.test_passage.success', result: result), class: 'text-success')
    elsif @test_passage.result >= TestPassage::SUCCESS_VALUE
      content_tag(:h2, t('helpers.test_passage.time',
                         result: result,
                         time: @test_passage.passage_duration,
                         duration: @test_passage.test.duration),
                  class: 'text-danger')
    else
      content_tag(:h2, t('helpers.test_passage.fail', result: result), class: 'text-danger')
    end
  end
end

app/helpers/tests_helper.rb
module TestsHelper
  def levels
    Test::LEVELS.map.with_index { |k, i| [i, I18n.t("helpers.test.#{k}")] }.to_h
  end

  def test_level(test)
    levels[test.level] || I18n.t('helpers.test.pro')
  end
end

app/views/admin/_navbar.html.erb
<nav class="navbar navbar-dark bg-info mb-3">
  <%= link_to t('.title'), root_path, class: 'navbar-brand logo__title' %>

  <div class="navbar-text">
    <%= t('.welcome') %> <strong><%= link_to current_user.name, guru_path %></strong>! |
    <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> |
    <%= render 'shared/langs' %>
  </div>
</nav>

app/views/layouts/_footer.html.erb
<footer class="footer d-flex justify-content-center text-light bg-dark mt-5">
  &copy; <%= current_year %>&ensp;
  <%= mail_to "tim@domain.com", 'Tim Arbaev', class: 'text-light footer_link' %>.&ensp;
  <%= link_to t('.project'), github_url('arbaev', 'testguru'),
              target: "_blank", class: 'text-light footer_link' %>&ensp;&mdash;&ensp;
  <%= link_to t('.school'),
              'http://thinknetica.com/',
              target: "_blank", class: 'text-light footer_link' %>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark mb-3">
  <%= link_to t('.title'), root_path, class: 'navbar-brand logo__title' %>

  <div class="navbar-text">
    <% if user_signed_in? %>
      <%= t('.welcome') %> <strong><%= link_to current_user.name, guru_path %></strong>! |
      <% if current_user.admin? %>
        <%= link_to t('.admintools'), admin_tests_path %> |
      <% end %>
      <%= link_to t('.logout'), destroy_user_session_path, method: :delete %> |
    <% else %>
      <%= link_to t('.login'), user_session_path %> |
      <%= link_to t('.signup'), new_user_registration_path %> |
    <% end %>

    <%= link_to t('.feedback'), new_feedback_path %> |
    <%= render 'shared/langs' %>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('.title') %></title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="d-flex flex-column">
  <%= render 'admin/navbar' %>
  <div class="container flex-fill">
    <%= render 'shared/flash' %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= locale %>">
  <head>
    <title><%= t('.title') %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <div class="container flex-fill">
      <%= render 'shared/flash' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if resource.present? && resource.errors.present? %>
  <%= content_tag :div, class: 'resource-errors', data: { resource_id: resource.try(:id) } do %>
    <h2>
      <%= t('.header', count: resource.errors.count) %>:
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% flash.each do |key, message| %>
  <%= content_tag :p, message.html_safe, class: "alert alert-#{key}" %>
<% end %>

app/views/shared/_langs.html.erb
<% if I18n.locale == I18n.default_locale %>
  <%= link_to t('.eng'), {lang: :en} %>
<% else %>
  <%= link_to t('.rus'), {lang: :ru} %>
<% end %>