config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'custom_sessions' }

  get 'guru', to: 'users#show'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline_form, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  # процент правильных ответов выше которого тест засчитывается успешно пройденным
  SUCCESS_VALUE = 85

  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question
  before_save :calc_result, if: :completed?

  def accept!(answer_ids)
    if in_time?
      self.score += 1 if correct_answer?(answer_ids)
      save!
    else
      self.current_question = nil
    end
  end

  def completed?
    current_question.nil?
  end

  def result_percentage
    score * 100 / test.total_questions
  end

  def successful?
    in_time? && result_percentage >= SUCCESS_VALUE if completed?
  end

  def question_number
    test.questions.order(:id).where('id <= ?', current_question).size
  end

  def passage_duration
    (Time.current - self.created_at).to_i
  end

  def remain_duration
    self.test.duration - passage_duration
  end

  private

  def before_validation_set_question
    self.current_question = next_question
  end

  def next_question
    if current_question.nil?
      test.questions.first
    else
      test.questions.order(:id).where('id > ?', current_question.id).first
    end
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == answer_ids.to_a.map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.right_answers
  end

  def calc_result
    self.result = result_percentage
  end

  def in_time?
    duration = test.duration

    duration.zero? || passage_duration <= duration
  end
end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_test_passage, only: %i[show update result gist]

  def show; end

  def result; end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      new_badges = UserBadgeService.new(@test_passage).give_badges
      @test_passage.user.badges.push(new_badges)

      # FIXME: отключено на время разработки беджей и таймера
      # TestsMailer.completed_test(@test_passage).deliver_now

      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  def gist
    gist_post = GistQuestionService.new(@test_passage.current_question)
    if gist_post.success?
      Gist.create!(url: gist_post.url,
                   user: @test_passage.user,
                   question: @test_passage.current_question)

      flash[:notice] = t('.success_html', url: gist_post.url)
    else
      flash[:alert] = t('.fail')
    end

    redirect_to @test_passage
  end

  private

  def find_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper
  def total_questions_helper
    t('helpers.test_passage.total', total: @test_passage.test.total_questions)
  end

  def result_message(result)
    if @test_passage.successful?
      content_tag(:h2, t('helpers.test_passage.success', result: result), class: 'text-success')
    elsif @test_passage.result >= TestPassage::SUCCESS_VALUE
      content_tag(:h2, t('helpers.test_passage.time',
                         result: result,
                         time: @test_passage.passage_duration,
                         duration: @test_passage.test.duration),
                  class: 'text-danger')
    else
      content_tag(:h2, t('helpers.test_passage.fail', result: result), class: 'text-danger')
    end
  end
end

app/views/test_passages/result.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>

<p><%= total_questions_helper %></p>

<p>
  <%= t('.correct_answers', score: @test_passage.score) %>
</p>

<%= result_message(@test_passage.result_percentage) %>

<%= link_to t('.back2tests'), tests_path %>

app/views/test_passages/show.html.erb
<h1><%= t('.header', title: @test_passage.test.title) %></h1>
<p><%= total_questions_helper %></p>

<% unless @test_passage.test.duration.zero? %>
  <div id="timer" data-duration="<%= @test_passage.remain_duration %>"></div>
<% end %>

<div class="progress">
  <%= content_tag :div,
                  class: "progress-bar",
                  data: { total: @test_passage.test.total_questions,
                          current: @test_passage.question_number },
                  role: "progressbar",
                  style: "width: 0%;",
                  'aria-valuenow' => "0",
                  'aria-valuemin' => "0",
                  'aria-valuemax' => "100" do %>
  <% end %>
</div>

<h2>
  <%= @test_passage.question_number %>. <%= @test_passage.current_question.body %>
</h2>

<%= form_with url: test_passage_path(@test_passage), local: true, id: :answer_form, method: :put do |form| %>
  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id, :body,
                                  include_hidden: false do |b| %>
    <p>
      <%= b.check_box id: "answer_ids_#{b.object.id}" %>
      <%= b.label %>
    </p>
  <% end %>
  <p>
    <%= link_to t('.create_gist'), gist_test_passage_path(@test_passage), method: :post %>
  </p>
  <%= form.submit t('.next'), class: 'btn btn-outline-info' %>
<% end %>