config/routes.rb
Rails.application.routes.draw do
  root 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { sessions: 'custom_sessions' }

  get 'guru', to: 'users#show'

  resources :feedbacks, only: %i[new create]
  resources :badges, only: :index

  resources :tests, only: :index do
    post :start, on: :member
  end

  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    root 'tests#index'
    resources :tests do
      patch :update_inline_form, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_ANSWERS = 4

  belongs_to :question

  validates :body, presence: true
  validate :validate_answers_quantity, on: :create

  scope :right_answers, -> { where(correct: true) }

  private

  def validate_answers_quantity
    if question.answers.count >= MAX_ANSWERS
      errors.add(:answers_quantity, I18n.t('activerecord.errors.messages.max_answers', max: MAX_ANSWERS))
    end
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_from_answer_not_found

  def show; end

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: t('.notice')
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question), notice: t('.notice')
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end

  def rescue_from_answer_not_found
    redirect_to admin_tests_path, alert: t('.alert.not_found')
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.erb
<tr>
  <td><%= answer.body %></td>
  <td><%= link_to t('.show'), admin_answer_path(answer) %></td>
  <td><%= link_to t('.edit'), edit_admin_answer_path(answer) %></td>
  <td><%= link_to t('.delete'), admin_answer_path(answer),
                  method: :delete,
                  data: {confirm: t('.sure')} %>
  </td>
</tr>

app/views/admin/answers/_form.html.erb
<div class="row m-3">
  <div class="col- col-sm-12 col-md-6">
    <%= form_with model: [:admin, @question, @answer], local: true do |form| %>
      <%= render 'shared/errors', resource: @answer %>

      <div class="form-group">
        <%= form.label :body %><br>
        <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60, class: 'form-control' %>
      </div>

      <div class="form-check mb-3">
        <%= form.label :correct, class: "form-check-label" do %>
          <%= form.check_box :correct, id: :answer_correct, class: 'form-check-input' %>
          <%= t('helpers.label.answer.correct') %>
        <% end %>
      </div>

      <%= form.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/answers/_nav.html.erb
<%= link_to t('.back2tests'), admin_tests_path %> |
<%= link_to t('.back2test'), admin_test_path(@answer.question.test) %> |
<%= link_to t('.back2quest'), admin_question_path(@answer.question) %>

app/views/admin/answers/edit.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= @answer.question.body %>
</p>

<%= render 'form' %>

<hr>
<%= render 'nav' %>

app/views/admin/answers/new.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= @question.body %>
</p>

<%= render 'form' %>

<hr>
<%= render 'nav' %>

app/views/admin/answers/show.html.erb
<h1><%= t('.header') %></h1>

<p>
  <%= @answer.question.body %>
</p>

<p>
  <b><%= t('.answer') %></b>
  <%= @answer.body %>
</p>

<p>
  <b><%= t('.correct') %></b>
  <%= @answer.correct %>
</p>
<%= render 'nav' %>